sudo: false
rvm: 2.4.0
os: linux
cache:
  bundler: true
  directories: $TRAVIS_BUILD_DIR/tmp/.htmlproofer
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - ca-certificates
notifications:
    email: false
